apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis

  serviceName: redis
  template:
    metadata:
      name: redis
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: tubetrue01/redis:5.0.7
          ports:
            - containerPort: 6379
              protocol: TCP
          command:
            - redis-server
            - "/redis-master/redis.conf"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /redis-master
              name: config
            - mountPath: /data
              name: redis-pvc
      volumes:
        - name: config
          configMap:
            name: redis
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
        labels:
          app: redis
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi


---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
      targetPort: 6379

#Create configMap
#Kubectl create configMap redis --from-file=redis.conf
