apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  clusterIP: None
  ports:
    - port: 9090
      name: server
      targetPort: 9090
    - port: 9091
      name: management
      targetPort: 9091
  selector:
    app: eureka-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
  labels:
    app: eureka-sever
spec:
  serviceName: eureka-server
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: tubetrue01/eureka-server:v1
          ports:
            - containerPort: 9090
              name: server
            - containerPort: 9091
              name: management
          env:
            - name: APP_NAME
              value: "eureka-server"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.appname=${APP_NAME}
                     --eureka.instance.hostname=${POD_NAME}.${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=false
                     --eureka.client.service-url.defaultZone=http://eureka-server-0.${APP_NAME}:9090/eureka,http://eureka-server-1.${APP_NAME}:9090/eureka
                     "
          resources:
            limits:
              cpu: 1000m
              memory: 252Mi
            requests:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 9091
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 9091
