apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1g-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /usr/local/data
    server: 192.168.0.111
