apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /usr/local/data
    server: 192.168.0.111
