apiVersion: v1
kind: Service
metadata:
  name: elastic-search
  labels:
    app: elastic-search
spec:
  selector:
    app: elastic-search
  clusterIP: None
  ports:
    - port: 9200
      name: restful
    - port: 9300
      name: inter-node

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elastic-search
spec:
  serviceName: elastic-search
  replicas: 1
  selector:
    matchLabels:
      app: elastic-search
  template:
    metadata:
      labels:
        app: elastic-search
    spec:
      containers:
        - name: elastic-search
          image: tubetrue01/elasticsearch-oss:7.5.2
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: restful
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: DISCOVERY.TYPE                # 注意大写
              value: single-node
            - name: cluster.initial_master_nodes  # 注意小写
              value: elastic-search-0
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.name
              value: elastic-search
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
