apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  labels:
    app: fluentd
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: default
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      # Open the annotation if you need to monitor the logs of master
      #      tolerations:
      #        - key: node-role.kubernetes.io/master
      #          effect: NoSchedule
      containers:
        - name: fluentd
          image: tubetrue01/fluentd:v1.8.1-debian-elasticsearch7-1.1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "elastic-search.default.svc.cluster.local"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
            - name: FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS
              value: "false"
            - name: FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR
              value: "true"
            - name: FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE
              value: "true"
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: springcloud-log
              mountPath: /var/log/springcloud/eureka-server
            - name: config-volume
              mountPath: /fluentd/etc/conf.d
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: springcloud-log
          hostPath:
            path: /var/log/springcloud/eureka-server

---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    app: fluentd
  ports:
    - port: 24224
      name: fluentd-expose
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
    </system>

  input.conf: |-
    <source>
        @type tail
        @id eureka-server_logs
        path /var/log/springcloud/eureka-server/eureka-server**/*.log
        pos_file /var/log/springcloud/eureka-server/fluentd.pos
        tag eureka-server
        <parse>
          @type multiline
          format_firstline /\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}\.\d{1,3}/
          format1 /^(?<time>\d{4}-\d{1,2}-\d{1,2}\s\d{1,2}:\d{1,2}:\d{1,2}\.\d{1,3})\s*(?<level>\[\w+\])\s(?<class>\(\w+.java\s*:\d{1,}\))---(?<message>.*)/
          formatN 20
        </parse>
    </source>
  output.conf: |-
    <match eureka-server>
      @id elasticsearch-eureka-server
      @type elasticsearch
      @log_level info
      # include_tag_key true
      host elastic-search
      port 9200
      logstash_format true
      request_timeout    30s
      logstash_prefix eureka-server
       <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 1
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>
