apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: tubetrue01/kibana:7.5.2
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 1000m
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elastic-search:9200  # Cluster DNS
          ports:
            - containerPort: 5601
