#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_1
#          uri: lb://user-consumer
#          predicates:
#            - Path=/consumer/**
#            - Weight=test,100
#        - id: test_2
#          uri: lb://user-provider
#          predicates:
#            - Path=/provider/**
#            - Weight=test,0
#
#      default-filters:
#        - name: Hystrix
#          args:
#            name: fallbackForward
#            fallbackUri: forward:/gateway/fallback
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 10
#        - name: Retry
#          args:
#            retries: 3
#      httpclient:
#        response-timeout: 2s
#
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#          include-expression: serviceId.endsWith('CONSUMER')
#hystrix:
#  threadpool:
#    HystrixGatewayFilterFactory:
#      coreSize: 100
#      maxQueueSize: 100
#      queueSizeRejectionThreshold: 80
#      maximumSize: 100
#  command:
#    fallbackForward:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillseconds: 5000
#          strategy: THREAD
#      circuitBreaker:
#        requestVolumeThreshold: 20
#        errorThresholdPercentage: 50
#        sleepWindowInMilliseconds: 5000
#        enabled: true
