#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: test_1
#          uri: lb://user-consumer
#          predicates:
#            - Path=/consumer/**
#            - Weight=test,50
#
#        - id: test_2
#          uri: lb://user-provider
#          predicates:
#            - Path=/provider/**
#            - Weight=test,50
#
#      default-filters:
#        - name: Hystrix
#          args:
#            name: fallbackForeward
#            fallbackUri: forward:/gateway/fallback
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 3
#        - name: Retry
#          args:
#            retries: 3
#      httpclient:
#        response-timeout: 2s
#    stream:
#      bindings:
#        hystrixStreamOutput:
#          destination: turbine
#
#    #      discovery:
#    #        locator:
#    #          enabled: true
#    #          lower-case-service-id: true
#    #          include-expression: serviceId.endsWith('CONSUMER')
#hystrix:
#  command:
#    fallbackForward:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds:7000
