server:
  port: 7070
  servlet:
    context-path: /consumer
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    stream:
      bindings:
        hystrixStreamOutput:
          destination: turbine
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 192.168.0.201
    port: 32567
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
    sender:
      type: rabbit

eureka:
  instance:
    hostname: localhost
    appname: user-consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 7071
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
  stream:
    queue:
      send-id: false
