server:
  port: 7070
  servlet:
    context-path: /userconsumer
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  instance:
    hostname: localhost
    appname: user-consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
management:
  server:
    port: 7071
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true
