server:
  port: 7070
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: 192.168.0.201
    port: 32567
    username: guest
    password: guest
eureka:
  instance:
    hostname: localhost
    appname: user-consumer
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 7071
feign:
  hystrix:
    enabled: true
