apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-consumer
  labels:
    app: user-consumer
  namespace: zpf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-consumer
  template:
    metadata:
      labels:
        app: user-consumer
    spec:
      containers:
        - name: user-consumer
          image: tubetrue01/user-consumer:v2
          ports:
            - containerPort: 7070
              name: server
            - containerPort: 7071
              name: management
          env:
            - name: APP_NAME
              value: "user-consumer"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_OPTS
              value: "
                     --spring.rabbitmq.host=rabbitmq
                     --spring.rabbitmq.username=guest
                     --spring.rabbitmq.password=guest
                     --spring.rabbitmq.port=5672
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.appname=${APP_NAME}
                     --eureka.instance.hostname=${POD_NAME}.${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=true
                     --eureka.client.service-url.defaultZone=http://root:root@eureka-server-0.eureka-server:9090/eureka,http://root:root@eureka-server-1.eureka-server:9090/eureka
                     "
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 7071
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 7071
          lifecycle:
            preStop:
              httpGet:
                httpHeaders:
                  - name: Authorization
                    value: Basic cm9vdDpyb290
                port: 7070
                path: /userconsumer/eureka/offline
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/log/springcloud/user-consumer
              name: log-path
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/springcloud/user-consumer
