apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 1010
      name: server
      targetPort: 1010
      nodePort: 30010
    - port: 1011
      name: management
      targetPort: 1011
      nodePort: 30011
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: tubetrue01/admin:v1
          ports:
            - containerPort: 1010
              name: server
            - containerPort: 1011
              name: management
          env:
            - name: APP_NAME
              value: "admin"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.appname=${APP_NAME}
                     --eureka.instance.hostname=${POD_NAME}.${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=true
                     --eureka.client.service-url.defaultZone=http://eureka-server-0.eureka-server:9090/eureka,http://eureka-server-1.eureka-server:9090/eureka
                     "
          resources:
            limits:
              cpu: 1000m
              memory: 252Mi
            requests:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 1011
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 1011
          lifecycle:
            preStop:
              httpGet:
                httpHeaders:
                  - name: Authorization
                    value: Basic cm9vdDpyb290
                port: 1010
                path: /eureka/offline
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/log/springcloud/admin
              name: log-path
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/springcloud/admin
