server:
  port: 1010
spring:
  application:
    name: admin
eureka:
  instance:
    appname: admin
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
management:
  server:
    port: 1011
  endpoints:
    web:
      exposure:
        include: "*"
