server:
  port: 1010
spring:
  application:
    name: admin
  security:
    user:
      name: root
      password: root
eureka:
  instance:
    appname: admin
    hostname: localhost
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://root:root@localhost:9090/eureka
management:
  server:
    port: 1010
  endpoints:
    web:
      exposure:
        include: "*"
