server:
  port:  3030
spring:
  application:
    name: sleuth-zipkin
  security:
    user:
      name: root
      password: root

zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.0.201:32567
      password: guest
      username: guest
      queue: zipkin

eureka:
  instance:
    hostname: localhost
    appname: sleuth-zipkin
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://root:root@localhost:9090/eureka

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 3031
