server:
  port: 8080
spring:
  application:
    name: user-provider
  datasource:
    url: jdbc:mysql://192.168.0.112:3306/test?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    password: root
    username: root
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 192.168.0.201
    port: 32567
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
    sender:
      type: rabbit
mybatis:
  type-aliases-package: org.tubetrue01.pojo
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 6000
eureka:
  instance:
    hostname: localhost
    appname: user-provider
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081
