apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  serviceName: gitlab
  template:
    metadata:
      name: gitlab
      labels:
        app: gitlab
    spec:
      serviceAccountName: gitlab
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce
          ports:
            - containerPort: 80
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: gitlab-pvc
  volumeClaimTemplates:
    - metadata:
        name: gitlab-pvc
        labels:
          app: gitlab
      spec:
        accessModes:  [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  clusterIP: None
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab
  labels:
    app: gitlab
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitlab
  labels:
    app: gitlab
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitlab
  labels:
    app: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitlab
subjects:
  - kind: ServiceAccount
    name: gitlab
