server:
  port: 9090
spring:
  application:
    name: eureka-server
  security:
    user:
      name: root
      password: root
eureka:
   instance:
     hostname: localhost
     appname: eureka-server
   client:
     fetch-registry: false
     register-with-eureka: false
     service-url:
       defaultZone: http://root:root@localhost:9090/eureka
management:
  server:
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
