apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
  namespace: demo
spec:
  selector:
    app: eureka-server
  type: ClusterIP
  ports:
    - port: 9090
      name: server
      targetPort: 9090
    - port: 9091
      name: management
      targetPort: 9091
  sessionAffinity: ClientIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
  labels:
    app: eureka-sever
  namespace: demo
spec:
  serviceName: eureka-server
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: tubetrue01/eureka-server:1.0.0
          ports:
            - containerPort: 9090
              name: server
            - containerPort: 9091
              name: management
          env:
            - name: APP_NAME
              value: "eureka-server"  # ServiceName
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_OPTS
              value: "
                     --spring.application.name=${APP_NAME}
                     --eureka.instance.appname=${APP_NAME}
                     --eureka.instance.hostname=${POD_NAME}.${APP_NAME}
                     --registerWithEureka=true
                     --fetchRegistry=true
                     --eureka.instance.preferIpAddress=true      # Must be true otherwise the openFeign can't resolve the host
                     --eureka.client.service-url.defaultZone=http://root:root@eureka-server-0.${APP_NAME}:9090/eureka,http://root:root@eureka-server-1.${APP_NAME}:9090/eureka
                     "
          resources:
            limits:
              cpu: 1000m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 5
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 9091
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Authorization
                  value: Basic cm9vdDpyb290
              path: /actuator/health
              port: 9091
          lifecycle:
            preStop:
              httpGet:
                httpHeaders:
                  - name: Authorization
                    value: Basic cm9vdDpyb290
                port: 9090
                path: /eureka/offline
          volumeMounts:
            - mountPath: /var/log/springcloud/eureka-server
              name: log-path
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/springcloud/eureka-server
