server:
  port: 4040
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: config-server
eureka:
  instance:
    appname: config-server
    hostname: localhost
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@localhost:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 4041
